const Capabilities = {
  GENESYS_AGENT_ASSIST_API_DOMAIN: 'GENESYS_AGENT_ASSIST_API_DOMAIN',
  GENESYS_AGENT_ASSIST_CLIENTID: 'GENESYS_AGENT_ASSIST_CLIENTID',
  GENESYS_AGENT_ASSIST_CLIENTSECRET: 'GENESYS_AGENT_ASSIST_CLIENTSECRET',
  GENESYS_AGENT_ASSIST_KNOWLEDGE_ID: 'GENESYS_AGENT_ASSIST_KNOWLEDGE_ID',
  GENESYS_AGENT_ASSIST_INCLUDE_DRAFTDOCS: 'GENESYS_AGENT_ASSIST_INCLUDE_DRAFTDOCS',
  GENESYS_AGENT_ASSIST_MAX_ANSWERS: 'GENESYS_AGENT_ASSIST_MAX_ANSWERS',
  GENESYS_AGENT_ASSIST_TIMEOUT: 'GENESYS_AGENT_ASSIST_TIMEOUT'
}

const Defaults = {
  [Capabilities.GENESYS_AGENT_ASSIST_API_DOMAIN]: 'mypurecloud.com',
  [Capabilities.GENESYS_AGENT_ASSIST_INCLUDE_DRAFTDOCS]: true,
  [Capabilities.GENESYS_AGENT_ASSIST_MAX_ANSWERS]: 5,
  [Capabilities.GENESYS_AGENT_ASSIST_TIMEOUT]: 10000
}

module.exports = {
  Capabilities,
  Defaults
}
